#config_version=4

####################
# Mode: Default
# In this mode here is what should happen...
####################

mode:
  priority: 100
  start_events: ball_starting
  stop_on_ball_end: True
