#config_version=4

####################
# Mode Properties
####################
mode:
    start_events: ball_starting
    stop_events: ball_ending
    priority: 100

####################
# Shots
####################
shots:
    skill_shot_a:
      switch: s_a_lane
      show_tokens:
        led: l_a
      profile: skill_shot_roaming_profile

    skill_shot_b:
      switch: s_b_lane
      show_tokens:
        led: l_b
      profile: skill_shot_roaming_profile

    skill_shot_c:
      switch: s_c_lane
      show_tokens:
        led: l_c
      profile: skill_shot_roaming_profile

    skill_shot_d:
      switch: s_d_lane
      show_tokens:
        led: l_d
      profile: skill_shot_roaming_profile

    skill_shot_a_and_d:
      switch: s_l_yellow_rollover
      show_tokens:
        led: l_a, l_d

    skill_shot_b_and_c:
      switch: s_r_yellow_rollover
      show_tokens:
        led: l_b, l_c


####################
# Base - Shows
####################
shows:
    skill_shot_inactive:
      - duration: -1
        leds:
          (led): white


    skill_shot_active:
      - duration: -1
        leds:
          (led): red


####################
# Base - Shot Profiles
####################
shot_profiles:
  skill_shot_roaming_profile:
      states:
        - name: inactive
           show: skill_shot_inactive
        - name: active
           show: skill_shot_active
      loop: yes

#  skill_shot_roaming_bonus_profile:
#      states:
#         - name: unlit  # step 1
#           show: off
#         - name: flashing  # step 2
#           show: flash
#         - name: lit  # step 3
#           show: on
#      loop: yes