#config_version=4

####################
# Game: Space Shuttle SEGA
#     http://www.ipdb.org/machine.cgi?id=5542
# Notable Features:
#     Flippers (2), Pop bumpers (2), Slingshots (2),
#     Standup targets (4),
#     Star rollovers (4),
#     Spinning targets (2),
#     Messenger ball (1),
#     Kick-out hole (1),
#     Your Number Match.
#     Drop-down cabinet.
#
# Created:
#     August 28, 2016
# Created by:
#     Jeremy T. Edwards - pinman2020@gmail.com
#
# Updated:
#     October 15, 2016
# Updated by:
#     Jeremy T. Edwards - pinman2020@gmail.com
# Version:
#     0.2
#
# Using vm
# $ . ~/pinball/v-mpf/bin/activate
# $ . ~/pinball/v-mpf/bin/deactivate
#
# Run monitor for testing game in real time (separate window)
# $ kivy -m mpf monitor
#
# To run table connected
# $ cd ~/pinball-games/space-shuttle_sega
# $ kivy -m mpf both
#
# To run table Vitural Mode
# (-X means don't talk to hardware)
# $ cd ~/pinball-games/space-shuttle_sega
# $ kivy -m mpf both -X
#
####################


####################
# Hardware
####################
## Comment out for testing without hardware
hardware:
    platform: fast
    driverboards: fast

fast:
    # ports for MAC
    ports: /dev/tty.usbserial-1413B, /dev/tty.usbserial-1413C

    # ports for PC
#    ports: com3, com4, com5


####################
# Virtual Platform Configuration
####################
virtual_platform_start_active_switches:
    s_ball_trough_1


####################
# Switches
####################
switches:
    ## 1 - Plumb Bob Tilt ##
    s_plumb_bob_tilt:
        number: 000
        platform: virtual

    ## 2 - Match Button - Yellow ##
    s_match_button:
        number: 000
        platform: virtual

    ## 3 - Credit Button - Red ##
    s_credit_button:
        number: 000
        platform: virtual

    ## 4 - Right Coin Chute ##
    s_right_coin_chute:
        number: 000
        platform: virtual

    ## 6 - Left Coin Chute ##
    s_left_coin_chute:
        number: 000
        platform: virtual

    ## 8 - High Score Reset ##
    s_high_score_reset:
        number: 000
        platform: virtual

    ## 03 - Ball Trough 1 ##
    s_ball_trough_1:
        number: 03

    ## 06 - Tower Eject Hole ##
    s_tower_eject:
        number: 06

    ## 08 - Top Left Yellow Rollover ##
    s_l_yellow_rollover:
        number: 08

    ## 09 - Top Right Yellow Rollover ##
    s_r_yellow_rollover:
        number: 09

    ## 0A - A Lane ##
    s_a_lane:
        number: 0A

    ## 0B - B Lane ##
    s_b_lane:
        number: 0B

    ## 0D - C Lane ##
    s_c_lane:
        number: 0D

    ## 0E - D Lane ##
    s_d_lane:
        number: 0E

    ## 07 - Left Red Match Stand up ##
    s_l_match_standup:
        number: 07

    ## 0C - Middle 10k Stand up ##
    s_m_10k_standup:
        number: 0C

    ## 0F - Right 5k Stand up ##
    s_r_5k_standup:
        number: 0F

    ## 1A - Right 10k Stand up - Captive Ball ##
    s_r_10k_standup:
        number: 1A

    ## 1B - Right Captive Ball 1 - Top ##
    s_r_captive_1:
        number: 1B

    ## 18 - Right Captive Ball 2 - Bottom ##
    s_r_captive_2:
        number: 18

    ## 15 - Left 5k Advance Bonus - Above Spinner ##
    s_l_5k_advance_bonus:
        number: 15

    ## 12 - Left Spinner ##
    s_l_spinner:
        number: 12
        type: NC

    ## 17 - Left Jet Bumper ##
    s_left_jet_bumper:
        number: 17

    ## 1D - Right Jet Bumper ##
    s_right_jet_bumper:
        number: 1D

    ## 13 - Middle Spinner##
    s_m_spinner:
        number: 13
        type: NC

    ## 16 - Center Star Rollover - Top 1 ##
    s_m_star_rollover_1:
        number: 16

    ## 11 - Center Star Rollover - Second From Top 2 ##
    s_m_star_rollover_2:
        number: 11

    ## 10 - Center Star Rollover - Third From Top 3 ##
    s_m_star_rollover_3:
        number: 10

    ## 05 - Center Star Rollover - Bottom 4 ##
    s_m_star_rollover_4:
        number: 05

    ## 14 - Left and Right Slingshot ##
    s_left_slingshot:
        number: 04

    ## 19 - Ball Launch Lane - Playfield Entry ##
    s_top_lane_entry:
        number: 19

    ## 01 - Left and Right Outlane Drain ##
    s_left_outlane:
        number: 01

    ## 02 - Left and Right Return Lane ##
    s_left_return_lane:
        number: 02

    ## Flippers (2) ##
    ## 1E - Right Flipper / Lane Change ##
    s_right_flipper:
        number: 1E

    ## 1F - Left Flipper / Lane Change ##
    s_left_flipper:
        number: 1F

    ## Match Button  ##
    s_match:
        number: 26

    ## Start Button ##
    s_start:
        number: 27
        tags: start
        type: NC


####################
# Coils
####################
coils:
    ## Flippers (2) ##
    c_left_flipper_main:
        number: 01
        pulse_ms: 20
        allow_enable: true
        hold_power: 2

    c_right_flipper_main:
        number: 02
        pulse_ms: 20
        allow_enable: true
        hold_power: 2

    ## Ball Trough Eject ##
    c_trough_eject:
        number: 03
        pulse_ms: 20

    ## Jet Bumpers (2) - Left, Right ##
    c_left_jet_bumper:
        number: 05
    c_right_jet_bumper:
        number: 06

    ## Right "Tower" Eject ##
    c_tower_eject:
        number: 00


####################
# Keyboard
####################
keyboard:
    s:
        switch: s_start
    z:
        switch: s_left_flipper
    /:
        switch: s_right_flipper
    y:
        switch: s_outhole
    o:
        switch: s_outhole
    1:
        switch: s_ball_trough_1
        toggle: true
    p:
        switch: s_ball_shooter_lane
        toggle: true
    l:
        switch: s_launch_button

## Playfield activated ##
    a:
        switch: s_top_lane_entry


####################
# Flippers
####################
flippers:
    left_flipper:
        main_coil: c_left_flipper_main
        activation_switch: s_left_flipper
#        enable_events: machine_reset_phase_3 #Comment out: enabled for testing
    right_flipper:
        main_coil: c_right_flipper_main
        activation_switch: s_right_flipper
#        enable_events: machine_reset_phase_3 #Comment out: enabled for testing


####################
# Ball Devices
####################
ball_devices:
    bd_trough:
        ball_switches: s_ball_trough_1
        eject_coil: c_trough_eject
        entrance_count_delay: 300ms
        tags: trough, home, drain, ball_add_live
        debug: True

    bd_tower_eject:
        ball_switches: s_tower_eject
        eject_coil: c_tower_eject
        eject_timeouts: 3s
        debug: True


####################
# Auto-Fire Coils
####################
autofire_coils:
    ## Jet Bumpers (2) - Left, Right
    left_jet:
        coil: c_left_jet_bumper
        switch: s_left_jet_bumper
    right_jet:
        coil: c_right_jet_bumper
        switch: s_right_jet_bumper


####################
# Lights - Playfield
####################
leds:
    l_planet:
        label: l_planet
        type: rgb
        number: 01
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_a_and_d:
        label: l_a_and_d
        type: rgb
        number: 02
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_b_and_c:
        label: l_b_and_c
        type: rgb
        number: 00
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_satellite:
        label: l_satellite
        type: rgb
        number: 03
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_a:
        label: l_top_lane_a
        type: rgb
        number: 04
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_b:
        label: l_top_lane_b
        type: rgb
        number: 05
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_5k_extra_ball:
        label: l_5k_extra_ball
        type: rgb
        number: 06
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_c:
        label: l_top_lane_c
        type: rgb
        number: 07
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_d:
        label: l_top_lane_d
        type: rgb
        number: 08
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True


####################
# Lights - General Illumination
####################
    l_gi_89:
        tags: gi_all
        type: grb
        number: 89
        default_color: ffffff
    l_gi_8A:
        tags: gi_all
        type: grb
        number: 8A
        default_color: ffffff
    l_gi_8B:
        tags: gi_all
        type: grb
        number: 8B
        default_color: ffffff
    l_gi_8C:
        tags: gi_all
        type: grb
        number: 8C
        default_color: ffffff
    l_gi_90:
        tags: gi_all
        type: grb
        number: 90
        default_color: ffffff
    l_gi_92:
        tags: gi_all
        type: grb
        number: 92
        default_color: ffffff
    l_gi_93:
        tags: gi_all
        type: grb
        number: 93
        default_color: ffffff
    l_gi_96:
        tags: gi_all
        type: grb
        number: 96
        default_color: ffffff
    l_gi_97:
        tags: gi_all
        type: grb
        number: 97
        default_color: ffffff
    l_gi_99:
        tags: gi_all
        type: grb
        number: 99
        default_color: ffffff
    l_gi_9A:
        tags: gi_all
        type: grb
        number: 9A
        default_color: ffffff
    l_gi_9B:
        tags: gi_all
        type: grb
        number: 9B
        default_color: ffffff
    l_gi_9C:
        tags: gi_all
        type: grb
        number: 9C
        default_color: ffffff
    l_gi_9D:
        tags: gi_all
        type: grb
        number: 9D
        default_color: ffffff
    l_gi_9E:
        tags: gi_all
        type: grb
        number: 9E
        default_color: ffffff
    l_gi_9F:
        tags: gi_all
        type: grb
        number: 9F
        default_color: ffffff
    l_gi_A2:
        tags: gi_all
        type: grb
        number: A2
        default_color: ffffff
    l_gi_A3:
        tags: gi_all
        type: grb
        number: A3
        default_color: ffffff
    l_gi_A6:
        tags: gi_all
        type: grb
        number: A6
        default_color: ffffff
    l_gi_A7:
        tags: gi_all
        type: grb
        number: A7
        default_color: ffffff
    l_gi_AB:
        tags: gi_all
        type: grb
        number: AB
        default_color: ffffff
    l_gi_AC:
        tags: gi_all
        type: grb
        number: AC
        default_color: ffffff
    l_gi_AD:
        tags: gi_all
        type: grb
        number: AD
        default_color: ffffff
    l_gi_AE:
        tags: gi_all
        type: grb
        number: AE
        default_color: ffffff
    l_gi_B0:
        tags: gi_all
        type: grb
        number: B0
        default_color: ffffff
    l_gi_B1:
        tags: gi_all
        type: grb
        number: B1
        default_color: ffffff


####################
# Modes
####################
#modes:
#  # Priority 1,000,000
#  - tilt

#  # Priority 500
#  - high_score

  # Priority 100
#  - base
#  - skill_shot


####################
# Players
####################

            
