#config_version=4

####################
# Game: Space Shuttle SEGA
#     http://www.ipdb.org/machine.cgi?id=5542
# Notable Features:
#     Flippers (2), Pop bumpers (2), Slingshots (2),
#     Standup targets (4),
#     Star rollovers (4),
#     Spinning targets (2),
#     Messenger ball (1),
#     Kick-out hole (1),
#     Your Number Match.
#     Drop-down cabinet.
#
# Created:
#     August 28, 2016
# Created by:
#     Jeremy T. Edwards - pinman2020@gmail.com
#
# Updated:
#     October 15, 2016
# Updated by:
#     Jeremy T. Edwards - pinman2020@gmail.com
# Version:
#     0.2
#
# Using vm
# $ . ~/pinball/v-mpf/bin/activate
# $ . ~/pinball/v-mpf/bin/deactivate
#
# Run monitor for testing game in real time (separate window)
# $ kivy -m mpf monitor
#
# To run table connected
# $ cd ~/pinball-games/space-shuttle_sega
# $ kivy -m mpf both
#
# To run table Vitural Mode
# (-X means don't talk to hardware)
# $ cd ~/pinball-games/space-shuttle_sega
# $ kivy -m mpf both -X
#
####################


####################
# Hardware
####################
## Comment out for testing without hardware
hardware:
    platform: fast
    driverboards: fast

fast:
    # ports for PC
#    ports: com3, com4, com5

    # ports for MAC
    ports: /dev/tty.usbserial-1413B, /dev/tty.usbserial-1413C


#################
# Virtual Platform Configuration
#################
virtual_platform_start_active_switches:
    s_ball_trough_1


####################
# Switches
####################
switches:
    ## 1 - Plumb Bob Tilt ##
#    s_plumb_bob_tilt:
#        number: 000

#    ## 2 - Match Button - Yellow ##
#    s_match_button:
#        number: 000
#
#    ## 3 - Credit Button - Red ##
#    s_credit_button:
#        number: 000

    ## 4 - Right Coin Chute ##
#    s_right_coin_chute:
#        number: 000

    ## 6 - Left Coin Chute ##
#    s_left_coin_chute:
#        number: 000

    ## 8 - High Score Reset ##
#    s_high_score_reset:
#        number: 000

    ## 11 - Ball Trough 1 ##
    s_ball_trough_1:
        number: 03

    ## 13 - Tower Eject Hole ##
    s_tower_eject:
        number: 06

    ## 15 - Top Left Yellow Rollover ##
    s_l_yellow_rollover:
        number: 08

    ## 15 - Top Right Yellow Rollover ##
    s_r_yellow_rollover:
        number: 09

    ## 15 - A Lane ##
    s_a_lane:
        number: 0A

    ## 16 - B Lane ##
    s_b_lane:
        number: 0B

    ## 14 - C Lane ##
    s_c_lane:
        number: 0D

    ## 14 - D Lane ##
    s_d_lane:
        number: 0E

    ## 14 - Left Red Match Stand up ##
    s_l_match_standup:
        number: 07

#    ## 14 - Middle 10k Stand up ##
#    s_m_10k_standup:
#        number: 000

    ## 14 - Right 5k Stand up ##
    s_r_5k_standup:
        number: 0F

    ## 14 - Right 10k Stand up - Captive Ball ##
    s_r_10k_standup:
        number: 1A

    ## 14 - Right Captive Ball 1 - Top ##
    s_r_captive_1:
        number: 1B

    ## 14 - Right Captive Ball 2 - Bottom ##
    s_r_captive_2:
        number: 18

    ## 14 - Left 5k Advance Bonus - Above Spinner ##
    s_l_5k_advance_bonus:
        number: 15

    ## 14 - Left Spinner ##
    s_l_spinner:
        number: 12

    ## 17 - Left Jet Bumper ##
    s_left_jet_bumper:
        number: 17

    ## 19 - Right Jet Bumper ##
    s_right_jet_bumper:
        number: 1D

    ## 14 - Middle Spinner##
    s_m_spinner:
        number: 13

    ## 14 - Center Star Rollover - Top 1 ##
    s_m_star_rollover_1:
        number: 16

    ## 14 - Center Star Rollover - Second From Top 2 ##
    s_m_star_rollover_2:
        number: 11

    ## 14 - Center Star Rollover - Third From Top 3 ##
    s_m_star_rollover_3:
        number: 10

    ## 14 - Center Star Rollover - Bottom 4 ##
    s_m_star_rollover_4:
        number: 05

    ## 18 - Left Kicker(Slingshot) ##
    s_left_slingshot:
        number: 04

    ## 20 - Right Kicker(Slingshot) ##
    s_right_slingshot:
        number: 04

    ## 23 - Top Lane Entry ##
    s_top_lane_entry:
        number: 19

    ## 37 - Left and Right Outlane Drain ##
    s_left_outlane:
        number: 01

    ## 38 - Left and Right Return Lane ##
    s_left_return_lane:
        number: 02

    ## Flippers (2) ##
    ## 00 - Right Flipper / Lane Change ##
    s_right_flipper:
        number: 1E

    ## 00 - Left Flipper / Lane Change ##
    s_left_flipper:
        number: 1F


## Switches - Used in Testing ##

    ## Start Button - [Used in Testing] ##
    s_start:
        number:
        tags: start

    ## Launch Button - [Used in Testing] ##
    s_launch_button:
        number:
        tags: launch


####################
# Coils
####################
coils:
#    ## Flippers (2) ##
#    c_left_flipper_main:
#        number: 000
#        pulse_ms: 20
#    c_left_flipper_hold:
#        number: 001
#        allow_enable: true
#    c_right_flipper_main:
#        number: 002
#        pulse_ms: 20
#    c_right_flipper_hold:
#        number: 003
#        allow_enable: true
#
#    ## Ball Trough Eject ##
#    c_trough_eject:
#        number: 004
#        pulse_ms: 20

    ## Slingshots (2) ##
    # N/A

#    ## Jet Bumpers (2) - Left, Right ##
#    c_left_jet_bumper:
#        number: 008
#    c_right_jet_bumper:
#        number: 009
#
#    ## Right "Tower" Eject ##
#    c_tower_eject:
#        number: 014


####################
# Keyboard
####################
keyboard:
    s:
        switch: s_start
    z:
        switch: s_left_flipper
    /:
        switch: s_right_flipper
    y:
        switch: s_outhole
    o:
        switch: s_outhole
    1:
        switch: s_ball_trough_1
        toggle: true
    p:
        switch: s_ball_shooter_lane
        toggle: true
    l:
        switch: s_launch_button

## Playfield activated ##
    a:
        switch: s_top_lane_entry


####################
# Flippers
####################
flippers:
    left_flipper:
        main_coil: c_left_flipper_main
        hold_coil: c_left_flipper_hold
        activation_switch: s_left_flipper
#        enable_events: machine_reset_phase_3
    right_flipper:
        main_coil: c_right_flipper_main
        hold_coil: c_right_flipper_hold
        activation_switch: s_right_flipper
#        enable_events: machine_reset_phase_3


####################
# Ball Devices
####################
ball_devices:
    bd_trough:
        ball_switches: s_ball_trough_1
        eject_coil: c_trough_eject
        entrance_count_delay: 300ms
        tags: trough, home, drain
        debug: True

    bd_tower_eject:
        ball_switches: s_tower_eject
        eject_coil: c_tower_eject
        eject_timeouts: 3s
        debug: True


####################
# Auto-Fire Coils
####################
autofire_coils:
    ## Slingshots (2) ##
    # N/A

    ## Jet Bumpers (2) - Left, Right
    left_jet:
        coil: c_left_jet_bumper
        switch: s_left_jet_bumper
    right_jet:
        coil: c_right_jet_bumper
        switch: s_right_jet_bumper


####################
# Modes
####################
#modes:
#  # Priority 1,000,000
#  - tilt

#  # Priority 500
#  - high_score

  # Priority 100
#  - base
#  - skill_shot



####################
# Lights
####################
leds:
    l_planet:
        label: l_planet
        type: rgb
        number: 01
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_a_and_d:
        label: l_a_and_d
        type: rgb
        number: 02
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_b_and_c:
        label: l_b_and_c
        type: rgb
        number: 00
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_satellite:
        label: l_satellite
        type: rgb
        number: 03
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_a:
        label: l_top_lane_a
        type: rgb
        number: 04
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_b:
        label: l_top_lane_b
        type: rgb
        number: 05
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_5k_extra_ball:
        label: l_5k_extra_ball
        type: rgb
        number: 06
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_c:
        label: l_top_lane_c
        type: rgb
        number: 07
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True

    l_d:
        label: l_top_lane_d
        type: rgb
        number: 08
        default_color: ffffff
        x: 0
        y: 0
        z: 0
        debug: True
