#config_version=4

####################
# Game: Space Shuttle SEGA
#     http://www.ipdb.org/machine.cgi?id=5542
# Notable Features:
#     Flippers (2), Pop bumpers (2), Slingshots (2),
#     Standup targets (4),
#     Star rollovers (4),
#     Spinning targets (2),
#     Messenger ball (1),
#     Kick-out hole (1),
#     Your Number Match.
#     Drop-down cabinet.
#
# Created:
#     August 28, 2016
# Created by:
#     Jeremy T. Edwards - jeremytedwards@gmail.com
#
# Updated:
#     August 28, 2016
# Updated by:
#     Jeremy T. Edwards - jeremytedwards@gmail.com
# Version:
#     0.1
#
# To start vm
# $ . ~/pinball/mpf/bin/activate
#
# To run table connected
# $ cd ~/pinball-games/space-shuttle_sega
# $ mpf both -v -b
#
# To run table Vitural Mode
# $ cd ~/pinball-games/space-shuttle_sega
# $ mpf -x -v
#
####################


####################
# Hardware
####################
## Commented out for testing without hardware
#hardware:
#    platform: fast
#    driverboards: fast
#    driverboards: wpc
#
#fast:
#    ports: com3, com4, com5


####################
# Switches
####################
switches:
    ## 1 - Plumb Bob Tilt ##
    s_plumb_bob_tilt:
        number:

    ## 2 - Match Button - Yellow ##
    s_match_button:
        number:

    ## 3 - Credit Button - Red ##
    s_credit_button:
        number:

    ## 4 - Right Coin Chute ##
    s_right_coin_chute:
        number:

    ## 5 - Not Used ##

    ## 6 - Left Coin Chute ##
    s_left_coin_chute:
        number:

    ## 7 - Slam Tilt ##
    s_slam_tilt:
        number:

    ## 8 - High Score Reset ##
    s_high_score_reset:
        number:

    ## 9 - Playfield Tilt ##
    s_playfield_tilt:
        number:

    ## 10 - Outhole ##
    s_outhole:
        number:

    ## 11 - Ball Trough 1 ##
    s_ball_trough_1:
        number: 03

    ## 12 - Ball Trough 2 ##
    s_ball_trough_2:
        number:

    ## 13 - Tower Eject Hole ##
    s_tower_eject:
        number:

    ## 15 - Top Left Yellow Rollover ##
    s_l_yellow_rollover:
        number: 08

    ## 15 - Top Right Yellow Rollover ##
    s_r_yellow_rollover:
        number: 09

    ## 15 - A Lane ##
    s_a_lane:
        number: 0A

    ## 16 - B Lane ##
    s_b_lane:
        number: 0B

    ## 14 - C Lane ##
    s_c_lane:
        number: 0D

    ## 14 - D Lane ##
    s_d_lane:
        number: 0E

    ## 14 - Left Red Match Stand up ##
    s_l_match_standup:
        number: 07

    ## 14 - Middle 10k Stand up ##
    s_m_10k_standup:
        number:

    ## 14 - Right 5k Stand up ##
    s_r_5k_standup:
        number: 0F

    ## 14 - Right 10k Stand up - Captive Ball ##
    s_r_10k_standup:
        number: 1A

    ## 14 - Right Captive Ball 1 - Top ##
    s_r_captive_1:
        number: 1B

    ## 14 - Right Captive Ball 2 - Bottom ##
    s_r_captive_2:
        number: 18


    ## 14 - Left 5k Advance Bonus - Above Spinner ##
    s_l_5k_advance_bonus:
        number: 15

    ## 14 - Left Spinner##
    s_l_spinner:
        number: 12

    ## 17 - Left Jet Bumper ##
    s_left_jet_bumper:
        number: 17

    ## 19 - Right Jet Bumper ##
    s_right_jet_bumper:
        number:

    ## 14 - Middle Spinner##
    s_m_spinner:
        number: 13

    ## 14 - Center Star Rollover - Top 1 ##
    s_m_star_rollover_1:
        number: 16
    ## 14 - Center Star Rollover - Second From Top 2 ##
    s_m_star_rollover_2:
        number: 11
    ## 14 - Center Star Rollover - Third From Top 3 ##
    s_m_star_rollover_3:
        number: 10
    ## 14 - Center Star Rollover - Bottom 4 ##
    s_m_star_rollover_4:
        number: 05

    ## 18 - Left Kicker(Slingshot) ##
    s_left_slingshot:
        number: 04

    ## 20 - Right Kicker(Slingshot) ##
    s_right_slingshot:
        number: 04

    ## 22 - Ball Shooter Lane ##
    s_ball_shooter_lane:
        number:

    ## 23 - Top Lane Entry ##
    s_top_lane_entry:
        number: 19

    ## 37 - Left Outlane Drain ##
    s_left_outlane:
        number: 01

    ## 38 - Left Return Lane ##
    s_left_return_lane:
        number: 02

    ## 39 - Right Outlane Drain ##
    s_right_outlane:
        number: 01

    ## 40 - Right Return Lane ##
    s_right_return_lane:
        number: 02

    ## Flippers (2) ##
    ## 00 - Right Flipper / Lane Change ##
    s_right_flipper:
        number: 1E

    ## 00 - Left Flipper / Lane Change ##
    s_left_flipper:
        number: 1F


## Switches - Used in Testing ##

    ## Start Button - [Used in Testing] ##
    s_start:
        number:
        tags: start

    ## Launch Button - [Used in Testing] ##
    s_launch_button:
        number:
        tags: launch


####################
# Coils
####################
coils:
    ## Flippers (2) ##
    c_left_flipper_main:
        number: 000
        pulse_ms: 20
    c_left_flipper_hold:
        number: 001
        allow_enable: true
    c_right_flipper_main:
        number: 002
        pulse_ms: 20
    c_right_flipper_hold:
        number: 003
        allow_enable: true

    ## Ball Trough Eject ##
    c_trough_eject:
        number: 004
        pulse_ms: 20

    ## Slingshots (2) ##
    c_left_slingshot:
        number: 006
    c_right_slingshot:
        number: 007

    ## Jet Bumpers (3) - Left, Right, Middle ##
    c_left_jet_bumper:
        number: 008
    c_right_jet_bumper:
        number: 009

    ## Right "Tower" Eject ##
    c_santa_eject:
        number: 014


## Coils - Used in Testing ##

    ## Shooter Lane Auto-launch ##
    c_plunger_eject:
        number: 099
        pulse_ms: 25


####################
# Keyboard
####################
keyboard:
    s:
        switch: s_start
    z:
        switch: s_left_flipper
    /:
        switch: s_right_flipper
    y:
        switch: s_outhole
    o:
        switch: s_outhole
    1:
        switch: s_ball_trough_1
        toggle: true
    2:
        switch: s_ball_trough_2
        toggle: true
    p:
        switch: s_ball_shooter_lane
        toggle: true
    l:
        switch: s_launch_button

## Playfield activated ##
    a:
        switch: s_spinout_counter


####################
# Flippers
####################
flippers:
    left_flipper:
        main_coil: c_left_flipper_main
        hold_coil: c_left_flipper_hold
        activation_switch: s_left_flipper
#        enable_events: machine_reset_phase_3
    right_flipper:
        main_coil: c_right_flipper_main
        hold_coil: c_right_flipper_hold
        activation_switch: s_right_flipper
#        enable_events: machine_reset_phase_3


####################
# Ball Devices
####################
ball_devices:
    bd_trough:
        ball_switches: s_ball_trough_1, s_ball_trough_2
        eject_coil: c_trough_eject
        eject_targets: bd_plunger
        entrance_count_delay: 300ms
        tags: trough, home, drain
        debug: yes

    bd_tower_eject:
        ball_switches: s_tower_eject
        eject_coil: c_tower_eject
        eject_timeouts: 3s
        debug: yes


    ## Shooter Lane Auto-launch ##
    ## Not in standard game ##
    bd_plunger:
        ball_switches: s_ball_shooter_lane
        eject_coil: c_plunger_eject
        eject_timeouts: 3s
        mechanical_eject: true
        player_controlled_eject_event: sw_launch
        tags: ball_add_live
        debug: yes


####################
# Auto-Fire Coils
####################
autofire_coils:
    ## Slingshots (2) ##
    left_slingshot:
        coil: c_left_slingshot
        switch: s_left_slingshot
    right_slingshot:
        coil: c_right_slingshot
        switch: s_right_slingshot

    ## Jet Bumpers (3) - Left, Right, Middle ##
    left_jet:
        coil: c_left_jet_bumper
        switch: s_left_jet_bumper
    right_jet:
        coil: c_right_jet_bumper
        switch: s_right_jet_bumper


####################
# Displays
####################
displays:
    window:
      width: 1280
      height: 800
      title: Your ultimate pinball
      resizable: false
      fullscreen: auto
      borderless: false
      exit_on_escape: true

    kivy_config:
      graphics:
            fbo: force-hardware
####################
# Slide Player
####################
slide_player:
    mc_ready: welcome_slide
    mode_attract_started: attract_started


####################
# Slides
####################
slides:
    welcome_slide:
      widgets:
        - type: text
          text: SEGA Pinball
          font_size: 50
          color: ffbf00
        - type: rectangle
          width: 240
          height: 60
    attract_started:
      widgets:
        - type: text
          text: ATTRACT MODE - PRESS START [s]


####################
# Modes
####################
modes:
#  # Priority 1,000,000
#  - tilt

#  # Priority 500
#  - high_score

  # Priority 100
  - base
  - skill_shot




#################
# Virtual Platform Configuration
#################
virtual_platform_start_active_switches:
    s_ball_trough_1
    s_ball_trough_2