#config_version=4

####################
# Mode: Skill Shot
# In this mode here is what should happen...
####################

mode:
  priority: 100
  start_events: ball_starting
  stop_events: # ball drops into spinout kickout
