#config_version=4

#################
# Game:
#     Taxi
#     http://www.ipdb.org/machine.cgi?id=2505
# Notable Features:
#     Flippers (2), Pop bumpers (3), Slingshots (2),
#     Kick-out holes (2), 3-bank drop targets (2),
#     Standup target (1).
#     A left-side catapult propels the ball airborne into a habitrail.
#     A plunger lane skill shot shoots the ball into the "Spin-Out" whirlpool
#     to score up to 100,000 points
#
# Created:
#     June 5, 2016
# Created by:
#     Jeremy T. Edwards - jeremytedwards@gmail.com
#
# Updated:
#     August 22, 2016
# Updated by:
#     Jeremy T. Edwards - jeremytedwards@gmail.com
# Version:
#     0.2
#
# To start vm
# $ . ~/pinball/mpf/bin/activate
#
# To run table connected
# $ cd ~/pinball/taxi
# $ mpf both -v -b
#
# To run table Vitural Mode
# $ cd ~/pinball/taxi
# $ mpf -x -v
#
#################

## Commented out for testing without hardware
#hardware:
#    platform: fast
#    driverboards: fast
#     driverboards: wpc
#
#
#fast:
#    ports: com3, com4, com5


switches:
    ## 1 - Plumb Bob Tilt ##
    s_plumb_bob_tilt:
        number: 001

    ## 2 - Not Used ##

    ## 3 - Credit Button ##
    s_credit_button:
        number: 003

    ## 4 - Right Coin Chute ##
    s_r_coin_chute:
        number: 004

    ## 5 - Not Used ##

    ## 6 - Left Coin Chute ##
    s_l_coin_chute:
        number: 006

    ## 7 - Slam Tilt ##
    s_slam_tilt:
        number: 007

    ## 8 - High Score Reset ##
    s_high_score_reset:
        number: 008

    ## 9 - Playfield Tilt ##
    s_playfield_tilt:
        number: 009

    ## 10 - Outhole ##
    s_outhole:
        number: 010

    ## 11 - Ball Trough 1 ##
    s_ball_trough_1:
        number: 011

    ## 12 - Ball Trough 2 ##
    s_ball_trough_2:
        number: 012

    ## 13 - JoyRide Eject Hole ##
    s_joyride_eject:
        number: 013

    ## 14 - C Lane ##
    s_c_lane:
        number: 014

    ## 15 - A Lane ##
    s_a_lane:
        number: 015

    ## 16 - B Lane ##
    s_b_lane:
        number: 016

    ## 17 - Left Jet Bumper ##
    s_l_jet_bumper:
        number: 017

    ## 18 - Left Kicker ##
    s_l_kicker:
        number: 018

    ## 19 - Right Jet Bumper ##
    s_r_jet_bumper:
        number: 019

    ## 20 - Right Kicker ##
    s_r_kicker:
        number: 020

    ## 21 - Lower Jet Bumper ##
    s_lower_jet_bumper:
        number: 021

    ## 22 - Ball Shooter Lane ##
    s_ball_shooter_lane:
        number: 022
        tags: playfield_active

    ## 23 - Top Lane Entry ##
    s_top_lane_entry:
        number: 023

    ## 24 - Carry Passengers Target ##
    s_carry_passengers_target:
        number: 024

    ## 25 - Left Ramp Entry ##
    s_l_ramp_entry:
        number: 025

    ## 26 - Right Ramp Entry ##
    s_r_ramp_entry:
        number: 026

    ## 27 - Lola 3-Bank Drop Target - Left ##
    s_l_lola_target:
        number: 027

    ## 28 - Lola 3-Bank Drop Target - Middle ##
    s_m_lola_target:
        number: 028

    ## 29 - Lola 3-Bank Drop Target - Right ##
    s_r_lola_target:
        number: 029

    ## 30 - Pinbot 3-Bank Drop Target - Top ##
    s_l_pinbot_target:
        number: 030

    ## 31 - Pinbot 3-Bank Drop Target - Middle ##
    s_m_pinbot_target:
        number: 031

    ## 32 - Pinbot 3-Bank Drop Target - Bottom ##
    s_r_pinbot_target:
        number: 032

    ## 33 - Right Ramp ##
    s_r_ramp:
        number: 033

    ## 34 - Left Ramp ##
    s_l_ramp:
        number: 034

    ## 35 - Drac Catapult ##
    s_drac_catapult:
        number: 35

    ## 36 - Pinbot Eject Hole ##
    s_pinbot_eject:
        number: 036

    ## 37 - Left Outlane Drain ##
    s_l_outlane:
        number: 037

    ## 38 - Left Return Lane ##
    s_l_return_lane:
        number: 038

    ## 39 - Right Outlane Drain ##
    s_r_outlane:
        number: 039

    ## 40 - Right Return Lane ##
    s_r_return_lane:
        number: 040

    ## 41 - Not Used ##

    ## 42 - Not Used  ##

    ## 43 - Spinout - Kickbig ##
    s_spinout_saucer:
        number: 043

    ## 44 - Spinout - Counter ##
    s_spinout_counter:
        number: 044
        
    ## 45 - Not Used ##
    ## 46 - Not Used ##
    ## 47 - Not Used ##
    ## 48 - Not Used ##
    ## 49 - Not Used ##
    ## 50 - Not Used ##
    ## 51 - Not Used ##
    ## 52 - Not Used ##
    ## 53 - Not Used ##
    ## 54 - Not Used ##
    ## 55 - Not Used ##
    ## 56 - Not Used ##
    
    ## Flippers (2) ##
    ## 57 - Right Flipper / Lane Change ##
    s_right_flipper:
        number: 057

    ## 58 - Left Flipper / Lane Change ##
    s_left_flipper:
        number: 058
    
    ## 59 - Not Used ##
    ## 60 - Not Used ##
    ## 61 - Not Used ##
    ## 62 - Not Used ##
    ## 63 - Not Used ##
    ## 64 - Not Used ##



#    ## Start Button ##
#    s_start:
#        number: 03
#        tags: start

#    ## Launch Button ##
#    s_launch_button:
#        number: 01
#        tags: launch


coils:
    ## Flippers (2) ##
    c_flipper_left_main:
        number: 00
        pulse_ms: 20
    c_flipper_left_hold:
        number: 01
        allow_enable: true
    c_flipper_right_main:
        number: 02
        pulse_ms: 20
    c_flipper_right_hold:
        number: 03
        allow_enable: true

    ## Ball Trough Eject (?) ##
    c_trough_eject:
        number: 04
        pulse_ms: 20

    ## Shooter Lane Auto-launch ##
    c_plunger_eject:
        number: 05
        pulse_ms: 25

    ## Slingshots (2) ##
    c_left_sling:
        number: 06
    c_right_sling:
        number: 07

    ## Pop bumpers (3) ##
    c_top_left_pop:
        number: 08
    c_top_right_pop:
        number: 09
    c_top_center_pop:
        number: 10

    ## Spin-Out ##
    c_spinout_saucer:
        number: 11

    ## Dracula ##
    c_dracula_saucer:
        number: 12

    ## Santa ##
    c_santa_saucer:
        number: 13

    ## Pinbot ##
    c_pinbot_saucer:
        number: 14

    ## 3-bank drop targets (2) ##
    ## Lola ##
    ## Pinbot ##


    ## Standup target (1) ##
    ## Santa ##


keyboard:
    s:
        switch: s_start
    z:
        switch: s_left_flipper
    /:
        switch: s_right_flipper
    1:
        switch: s_trough1
        toggle: true
    2:
        switch: s_trough2
        toggle: true
    3:
        switch: s_trough3
        toggle: true
    4:
        switch: s_trough4
        toggle: true
    5:
        switch: s_trough5
        toggle: true
    6:
        switch: s_trough6
        toggle: true
    p:
        switch: s_ball_shooter_lane
        toggle: true
    l:
        switch: s_launch_button

    # Playfield activated #
    a:
        switch: s_spinout


flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
#        enable_events: machine_reset_phase_3
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
#        enable_events: machine_reset_phase_3


ball_devices:
    bd_trough:
        ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
        eject_coil: c_trough_eject
        eject_targets: bd_plunger
        entrance_count_delay: 300ms
        tags: trough, home, drain
        debug: yes
    bd_plunger:
        ball_switches: s_ball_shooter_lane
        eject_coil: c_plunger_eject
        eject_timeouts: 3s
        mechanical_eject: true
        player_controlled_eject_event: sw_launch
        tags: ball_add_live
        debug: yes

displays:
    window:
        width: 800
        height: 600


slide_player:
    mc_ready: welcome_slide
    mode_attract_started: attract_started
    ball_started: ball_started


slides:
    welcome_slide:
      widgets:
        - type: text
          text: Player 1
          font_size: 50
          color: ffbf00
        - type: rectangle
          width: 240
          height: 60
    attract_started:
      widgets:
        - type: text
          text: ATTRACT MODE - PRESS START
    ball_started:
      widgets:
        - type: text
          text: PLAYER (number) BALL (ball)


#################
# Virtual Platform Configuration
#################
virtual_platform_start_active_switches:
    s_trough1
    s_trough2
    s_trough3
    s_trough4
    s_trough5
    s_trough6