#config_version=4

####################
# Game: Taxi
#     http://www.ipdb.org/machine.cgi?id=2505
# Notable Features:
#     Flippers (2), Pop bumpers (3), Slingshots (2),
#     Kick-out holes (2), 3-bank drop targets (2),
#     Standup target (1).
#     A left-side catapult propels the ball airborne into a habitrail.
#     A plunger lane skill shot shoots the ball into the "Spin-Out" whirlpool
#     to score up to 100,000 points
#
# Created:
#     June 5, 2016
# Created by:
#     Jeremy T. Edwards - pinman2020@gmail.com
#
# Updated:
#     August 22, 2016
# Updated by:
#     Jeremy T. Edwards - pinman2020@gmail.com
# Version:
#     0.2
#
# To start vm
# $ . ~/pinball/mpf/bin/activate
#
# To run table connected
# $ cd ~/pinball/taxi
# $ mpf both -v -b
#
# To run table Vitural Mode
# $ cd ~/pinball/taxi
# $ mpf -x -v
#
####################


####################
# Hardware
####################
## Commented out for testing without hardware
#hardware:
#    platform: fast
#    driverboards: fast
#    driverboards: wpc
#
#fast:
#    ports: com3, com4, com5


####################
# Switches
####################
switches:
    ## 1 - Plumb Bob Tilt ##
    s_plumb_bob_tilt:
        number: 001

    ## 2 - Not Used ##

    ## 3 - Credit Button ##
    s_credit_button:
        number: 003

    ## 4 - Right Coin Chute ##
    s_right_coin_chute:
        number: 004

    ## 5 - Not Used ##

    ## 6 - Left Coin Chute ##
    s_left_coin_chute:
        number: 006

    ## 7 - Slam Tilt ##
    s_slam_tilt:
        number: 007

    ## 8 - High Score Reset ##
    s_high_score_reset:
        number: 008

    ## 9 - Playfield Tilt ##
    s_playfield_tilt:
        number: 009

    ## 10 - Outhole ##
    s_outhole:
        number: 010

    ## 11 - Ball Trough 1 ##
    s_ball_trough_1:
        number: 011

    ## 12 - Ball Trough 2 ##
    s_ball_trough_2:
        number: 012

    ## 13 - JoyRide(Santa) Eject Hole ##
    s_santa_eject:
        number: 013

    ## 14 - C Lane ##
    s_c_lane:
        number: 014

    ## 15 - A Lane ##
    s_a_lane:
        number: 015

    ## 16 - B Lane ##
    s_b_lane:
        number: 016

    ## 17 - Left Jet Bumper ##
    s_left_jet_bumper:
        number: 017

    ## 18 - Left Kicker(Slingshot) ##
    s_left_slingshot:
        number: 018

    ## 19 - Right Jet Bumper ##
    s_right_jet_bumper:
        number: 019

    ## 20 - Right Kicker(Slingshot) ##
    s_right_slingshot:
        number: 020

    ## 21 - Lower(middle) Jet Bumper ##
    s_middle_jet_bumper:
        number: 021

    ## 22 - Ball Shooter Lane ##
    s_ball_shooter_lane:
        number: 022

    ## 23 - Top Lane Entry ##
    s_top_lane_entry:
        number: 023

    ## 24 - Carry Passengers Target ##
    s_carry_passengers_target:
        number: 024

    ## 25 - Left Ramp Entry ##
    s_left_ramp_entry:
        number: 025

    ## 26 - Right Ramp Entry ##
    s_right_ramp_entry:
        number: 026

    ## 27 - Lola 3-Bank Drop Target - Left ##
    s_left_lola_target:
        number: 027

    ## 28 - Lola 3-Bank Drop Target - Middle ##
    s_middle_lola_target:
        number: 028

    ## 29 - Lola 3-Bank Drop Target - Right ##
    s_right_lola_target:
        number: 029

    ## 30 - Pinbot 3-Bank Drop Target - Top ##
    s_left_pinbot_target:
        number: 030

    ## 31 - Pinbot 3-Bank Drop Target - Middle ##
    s_middle_pinbot_target:
        number: 031

    ## 32 - Pinbot 3-Bank Drop Target - Bottom ##
    s_right_pinbot_target:
        number: 032

    ## 33 - Right Ramp ##
    s_right_ramp:
        number: 033

    ## 34 - Left Ramp ##
    s_left_ramp:
        number: 034

    ## 35 - Dracula Catapult ##
    s_dracula_catapult:
        number: 35

    ## 36 - Pinbot Eject Hole ##
    s_pinbot_eject:
        number: 036

    ## 37 - Left Outlane Drain ##
    s_left_outlane:
        number: 037

    ## 38 - Left Return Lane ##
    s_left_return_lane:
        number: 038

    ## 39 - Right Outlane Drain ##
    s_right_outlane:
        number: 039

    ## 40 - Right Return Lane ##
    s_right_return_lane:
        number: 040

    ## 41 - Not Used ##

    ## 42 - Not Used  ##

    ## 43 - Spinout - Kickbig ##
    s_spinout_kickout:
        number: 043

    ## 44 - Spinout - Counter ##
    s_spinout_counter:
        number: 044
        tags: playfield_active

    ## 45 - Not Used ##
    ## 46 - Not Used ##
    ## 47 - Not Used ##
    ## 48 - Not Used ##
    ## 49 - Not Used ##
    ## 50 - Not Used ##
    ## 51 - Not Used ##
    ## 52 - Not Used ##
    ## 53 - Not Used ##
    ## 54 - Not Used ##
    ## 55 - Not Used ##
    ## 56 - Not Used ##
    
    ## Flippers (2) ##
    ## 57 - Right Flipper / Lane Change ##
    s_right_flipper:
        number: 057

    ## 58 - Left Flipper / Lane Change ##
    s_left_flipper:
        number: 058
    
    ## 59 - Not Used ##
    ## 60 - Not Used ##
    ## 61 - Not Used ##
    ## 62 - Not Used ##
    ## 63 - Not Used ##
    ## 64 - Not Used ##

## Switches - Used in Testing ##

    ## Start Button - [Used in Testing] ##
    s_start:
        number: 098
        tags: start

    ## Launch Button - [Used in Testing] ##
    s_launch_button:
        number: 099
        tags: launch


####################
# Coils
####################
coils:
    ## Flippers (2) ##
    c_left_flipper_main:
        number: 000
        pulse_ms: 20
    c_left_flipper_hold:
        number: 001
        allow_enable: true
    c_right_flipper_main:
        number: 002
        pulse_ms: 20
    c_right_flipper_hold:
        number: 003
        allow_enable: true

    ## Ball Trough Eject ##
    c_trough_eject:
        number: 004
        pulse_ms: 20

    ## Slingshots (2) ##
    c_left_slingshot:
        number: 006
    c_right_slingshot:
        number: 007

    ## Jet Bumpers (3) - Left, Right, Middle ##
    c_left_jet_bumper:
        number: 008
    c_right_jet_bumper:
        number: 009
    c_middle_jet_bumper:
        number: 010

    ## Spin-Out - Kickout ##
    c_spinout_kickout:
        number: 011

    ## Dracula - Catapult ##
    c_dracula_catapult:
        number: 012

    ## JoyRide(Santa) - Saucer Eject ##
    c_santa_eject:
        number: 014

#    c_santa_kickout:
#        number: 013

    ## Pinbot - Saucer Eject ##
    c_pinbot_eject:
        number: 015

    ## Lola - 3-bank drop targets (2) - Reset ##
    ## Not in standard game ##

    ## Pinbot - 3-bank drop targets (2) - Reset ##
    ## Not in standard game ##

## Coils - Used in Testing ##

    ## Shooter Lane Auto-launch ##
    c_plunger_eject:
        number: 099
        pulse_ms: 25

####################
# Keyboard
####################
keyboard:
    s:
        switch: s_start
    z:
        switch: s_left_flipper
    /:
        switch: s_right_flipper
    y:
        switch: s_outhole
    o:
        switch: s_outhole
    1:
        switch: s_ball_trough_1
        toggle: true
    2:
        switch: s_ball_trough_2
        toggle: true
    p:
        switch: s_ball_shooter_lane
        toggle: true
    l:
        switch: s_launch_button

## Playfield activated ##
    a:
        switch: s_spinout_counter


####################
# Flippers
####################
flippers:
    left_flipper:
        main_coil: c_left_flipper_main
        hold_coil: c_left_flipper_hold
        activation_switch: s_left_flipper
#        enable_events: machine_reset_phase_3
    right_flipper:
        main_coil: c_right_flipper_main
        hold_coil: c_right_flipper_hold
        activation_switch: s_right_flipper
#        enable_events: machine_reset_phase_3


####################
# Ball Devices
####################
ball_devices:
    bd_trough:
        ball_switches: s_ball_trough_1, s_ball_trough_2
        eject_coil: c_trough_eject
        eject_targets: bd_plunger
        entrance_count_delay: 300ms
        tags: trough, home, drain
        debug: yes

    bd_spinout_kickout:
        ball_switches: s_spinout_kickout
        eject_coil: c_spinout_kickout
        eject_timeouts: 3s
        debug: yes

#    bd_santa_kickout:
#        ball_switches: s_santa_kickout
#        eject_coil: c_santa_kickout
#        eject_timeouts: 3s
#        debug: yes

    bd_santa_eject:
        ball_switches: s_santa_eject
        eject_coil: c_santa_eject
        eject_timeouts: 3s
        debug: yes

    bd_dracula_catapult:
        ball_switches: s_dracula_catapult
        eject_coil: c_dracula_catapult
        eject_timeouts: 3s
        debug: yes

    bd_pinbot_eject:
        ball_switches: s_pinbot_eject
        eject_coil: c_pinbot_eject
        eject_timeouts: 3s
        debug: yes

    ## Shooter Lane Auto-launch ##
    ## Not in standard game ##
    bd_plunger:
        ball_switches: s_ball_shooter_lane
        eject_coil: c_plunger_eject
        eject_timeouts: 3s
        mechanical_eject: true
        player_controlled_eject_event: sw_launch
        tags: ball_add_live
        debug: yes


####################
# Auto-Fire Coils
####################
autofire_coils:
    ## Slingshots (2) ##
    left_slingshot:
        coil: c_left_slingshot
        switch: s_left_slingshot
    right_slingshot:
        coil: c_right_slingshot
        switch: s_right_slingshot

    ## Jet Bumpers (3) - Left, Right, Middle ##
    left_jet:
        coil: c_left_jet_bumper
        switch: s_left_jet_bumper
    right_jet:
        coil: c_right_jet_bumper
        switch: s_right_jet_bumper
    middle_jet:
        coil: c_middle_jet_bumper
        switch: s_middle_jet_bumper



####################
# Displays
####################
displays:
    window:
        width: 800
        height: 600


####################
# Slide Player
####################
slide_player:
    mc_ready: welcome_slide
    mode_attract_started: attract_started


####################
# Slides
####################
slides:
    welcome_slide:
      widgets:
        - type: text
          text: Welcome
          font_size: 50
          color: ffbf00
        - type: rectangle
          width: 240
          height: 60

slide_player:
    init_done: welcome_slide

####################
# Modes
####################
modes:
#  # Priority 1,000,000
#  - tilt

#  # Priority 500
#  - high_score

  # Priority 100
  - base
  - skill_shot




#################
# Virtual Platform Configuration
#################
virtual_platform_start_active_switches:
    s_ball_trough_1
    s_ball_trough_2