#config_version=4

show_player:
    mode_attract_started:
      attract_abcd_show:
        action: play
        loops: -1
      attact_gi_show:
        action: play
        loops: -1
    mode_attract_stopped:
      attract_abcd_show:
        action: stop
      attact_gi_show:
        action: stop