#config_version=4

####################
# Mode Properties
####################
mode:
    start_events: ball_starting
    stop_events: sw_skillshot_end, ball_ending
    priority: 100


####################
# Skillshot - Shots
####################
shots:
    skillshot_a:
      switch: s_a_lane
      show_tokens:
        led: l_a
      profile: skillshot_roaming_profile
      advance_events: mode_skillshot_started

    skillshot_b:
      switch: s_b_lane
      show_tokens:
        led: l_b
      profile: skillshot_roaming_profile

    skillshot_c:
      switch: s_c_lane
      show_tokens:
        led: l_c
      profile: skillshot_roaming_profile

    skillshot_d:
      switch: s_d_lane
      show_tokens:
        led: l_d
      profile: skillshot_roaming_profile


####################
# Skillshot - Shot Groups
####################
shot_groups:
    skillshot:
      shots: skillshot_a, skillshot_b, skillshot_c, skillshot_d
      rotate_events: timer_rotate_skillshot_tick
      debug: True


####################
# Skillshot - Shows
####################
shows:
    skillshot_inactive:
      - duration: -1
        leds:
          (led): white

    skillshot_active:
      - duration: -1
        leds:
          (led): red


####################
# Skillshot - Shot Profiles
####################
shot_profiles:
  skillshot_roaming_profile:
      states:
        - name: inactive
          show: skillshot_inactive
        - name: active
          show: skillshot_active
      loop: yes


####################
# Skillshot - Timers
####################
timers:
  rotate_skillshot:
    start_running: True
    tick_interval: 1s